config/routes.rb
Rails.application.routes.draw do
  root "flint#index"

  get 'privacy-policy' => 'flint#privacyPolicy'

  resources :restaurants
  get 'restaurant/edit' => 'restaurants#edit'

  resources :messages

  devise_for :users, :controllers => {
    :omniauth_callbacks => 'users/omniauth_callbacks',
    :registrations => 'users/registrations'
  }

  get 'addLike' => 'flint#addLike'
  get 'updateMatch' => 'flint#updateMatch'
  get 'match' => 'flint#match'
  get 'user' => 'flint#user'
  get 'show/:id' => 'flint#show'
  get 'notification' => 'notifications#index'
  get 'create/:url' => "restaurant#create"

end

app/models/message.rb
class Message < ActiveRecord::Base
    # validates :title, :presence => true, :length => { :maximum => 10 }
    validates :body, :presence => true, :length => { :maximum => 100 }
    belongs_to :user_like
    belongs_to :user
    belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"
    belongs_to :sender, class_name: "User", foreign_key: "sender_id"
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def show
    @userlike = UserLike.find(params[:id])
    @matching = @userlike.matching

    if @userlike.like.gender == "male"
      @payment_user = @userlike.like
    elsif @userlike.liker.gender == "male"
      @payment_user = @userlike.liker
    end

    if @matching <= 2 # 奢るよと男から言っている
      @user_id = @userlike.user_id
      @like_id = current_user.id
    elsif @matching == 3 # 普通にマッチ
      if current_user.gender == "male"
        @user_id = @userlike.user_id
        @like_id = current_user.id
      elsif current_user.gender == "female"
        @user_id = current_user.id
        @like_id = @userlike.like_id
      end
    elsif @matching == 4 # 男から女へ、奢るよという誘いがあってマッチ成立
      if current_user.gender == "male"
        @user_id = current_user.id
        @like_id = @userlike.like_id
      elsif current_user.gender == "female"
        @user_id = @userlike.user_id
        @like_id = current_user.id
      end
    else
      render text: "something wrong"
    end
      @messages = Message.where(:user_like_id => @userlike.id)
      @users = User.all
  end

  # 書き込み
  def create
    userlike = UserLike.where(:id => params[:id]).first
    if userlike.user_id == current_user.id
      receiver_id = userlike.like_id
    elsif userlike.like_id == current_user.id
      receiver_id = userlike.user_id
    else
      render text: "something wrong"
    end
  	@message = Message.create(:user_like_id => params[:id], :body => params[:body], :sender_id => current_user.id, :receiver_id => receiver_id)
    redirect_to message_path(params[:id])
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/show.html.erb
<!-- メッセージ画面 -->
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="main">
        <div class="male-msg">
          <div class="male-msg-top">
            <div class="male-msg-top-inner">
              <div class="male-msg-top-img">
                <img src="<%= @userlike.restaurant.image %>" alt="image" />
              </div>
              <div class="male-msg-top-text">
                <h4><%= @userlike.restaurant.name %></h4>
                <ul class="woman-pick-list">
                  <li>
                    <% for starNum in 1..@userlike.restaurant.star do %>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <% end %>
                  </li>
                  <li>
                    <%= @userlike.restaurant.star %>
                  </li>
                  <li>
                    <!-- 2：奢るよと男から言っている -->
                    <% if @userlike.matching == 2 %>
                    <div class="btn-danger btn-xs disabled">
                      <%= @payment_user.name %>さんがごちそうしてくれるといってます！
                    </div>
                    <!-- 4：男から女へ、奢るよという誘いがあってマッチ成立 -->
                    <% elsif @userlike.matching == 4 %>
                    <div class="btn-danger btn-xs disabled">
                      <%= @payment_user.name %>さんがごちそうしてくれます！
                    </div>
                    <% else %>
                    <!-- 0：行かない -->
                    <% if  @userlike.restaurant.payment == 0 %>
                    <div class="btn-danger btn-xs disabled">
                      <!-- <%= @payment_user.name %>さんがごちそうしてくれるといってます！ -->
                    </div>
                    <!-- 1：片方が行きたいと言っている -->
                    <% elsif @userlike.restaurant.payment == 1 %>
                    <div class="btn-danger btn-xs disabled">
                      <%= @payment_user.name %>さんとワリカンでいきましょう！
                    </div>
                    <% else %>
                    <% end %>
                    <% end %>
                  </li>
                </ul>

                <ul class="woman-pick-list">
                  <li>
                    <span class="border-text">店の価格</span>
                    <span><%= @userlike.restaurant.price %></span>
                  </li>
                  <li>
                    <span class="border-text">エリア</span>
                    <span><%= @userlike.restaurant.area %></span>
                  </li>
                </ul>

                <!-- 1：片方が行きたいと言っている -->
                <% if @matching == 1 %>
                <% if current_user.gender == "male" %>
                <% if @userlike.like.gender =="male" %>
                <p class = "btn btn-default"><%= link_to "✕", :controller => "flint", :action => "updateMatch", :userlike_id => @userlike.id, :matching => 0,:method => :post %></p>
                <p class = "btn btn-default"><%= link_to "ワリカン！", :controller => "flint", :action => "updateMatch", :userlike_id => @userlike.id, :matching => 3,:method => :post %></p>
                <p class = "btn btn-default"><%= link_to "おごる！", :controller => "flint", :action => "updateMatch", :userlike_id => @userlike.id, :matching => 4,:method => :post %></p>
                <% elsif current_user.gender == "female" %>
                <% elsif @userlike.like.gender =="female" %>
                <p class = "btn btn-default"><%= link_to "お断りする", :controller => "flint", :action => "updateMatch", :userlike_id => @userlike.id, :matching => 0,:method => :post %></p>
                <p class = "btn btn-default"><%= link_to "お誘いを受ける", :controller => "flint", :action => "updateMatch", :userlike_id => @userlike.id, :matching => 3,:method => :post %></p>
                <% else %>
                <% end %>

                <!-- 2：奢るよと男から言っている -->
                <% elsif @matching == 2 %>
                <% elsif current_user.gender == "female" %>
                <p class = "btn btn-default"><%= link_to "お断りする", :controller => "flint", :action => "updateMatch", :userlike_id => @userlike.id, :matching => 0,:method => :post %></p>
                <p class = "btn btn-default"><%= link_to "お誘いを受ける", :controller => "flint", :action => "updateMatch", :userlike_id => @userlike.id, :matching => 4,:method => :post %></p>
                <% else %>
                <% end %>
                <% end %>
              </div>
            </div>
          </div>

          <!-- メッセージ一覧 -->
          <div class="male-msg-med">
            <p class="lead text-center"><%= @userlike.restaurant.user.id %>：<%= @userlike.restaurant.user.name %></p>
            <% @messages.each do |message| %>
              <div class="male-msg-comm-list row">
                <!-- 自分のメッセージ -->
                <% if message.sender_id == current_user.id%>
                  <li class="left">
                    <div class="baloon-right">
                      <%= message.body %>
                    </div>

                  </li>
                <!-- 相手のメッセージ -->
                <% elsif message.sender_id != current_user.id %>
                  <li class="right">
                  <div class="col-xs-4">
                    <div class="comm-img">
                        <% if current_user.id == @userlike.restaurant.user.id %>
                        <div class="pick-profile-pic-trim" style="width: 50px; height: 50px;">
                          <img src="<%= @users.find(@userlike.liker.id).thumb %>" alt="...">
                        </div>
                          <%= @userlike.liker.name %>
                        <% else %>
                        <div class="pick-profile-pic-trim" style="width: 50px; height: 50px;">
                          <img src="<%= @users.find(@userlike.like.id).thumb %>" alt="...">
                        </div>
                          <%= @userlike.like.name %>
                        <% end %>
                    </div>
                  </div>

                  <div class="col-xs-8">
                    <div class="baloon-left col-xs-9">
                      <%= message.body %>
                    </div>
                  </div>
                  </li>
                <% end %>
              </div>
            <% end %>
          </div>

          <!-- メッセージ入力欄 -->
          <%= form_tag(messages_path(), method: 'post') do %>
          <input type="text" name="body"></input>
          <input name="id" type="hidden" value="<%= @userlike.id %>" />

          <button type="button" class="btn btn-default btn-xs"><%= submit_tag "send", :sender_id => current_user.id , :receiver_id => @userlike.restaurant.user.name %></button>
          <% end %>

          <!-- トップに戻るボタン -->
          <div class="male-msg-footer clearfix">
            <div class="pull-left">
              <a href="/"><i class="fa fa-home fa-fw" aria-hidden="true"></i>&nbsp; Home</a>
            </div>
            <div class="pull-right">
              Some Text
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>