config/routes.rb
Rails.application.routes.draw do
  root "flint#index"

  get 'privacy-policy' => 'flint#privacyPolicy'

  resources :restaurants
  get 'restaurant/edit' => 'restaurants#edit'

  resources :messages

  devise_for :users, :controllers => {
    :omniauth_callbacks => 'users/omniauth_callbacks',
    :registrations => 'users/registrations'
  }

  get 'addLike' => 'flint#addLike'
  get 'updateMatch' => 'flint#updateMatch'
  get 'match' => 'flint#match'
  get 'user' => 'flint#user'
  get 'show/:id' => 'flint#show'
  get 'notification' => 'notifications#index'
  get 'create/:url' => "restaurant#create"

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
    belongs_to :user
    has_many :user_likes

    # validates :comment, presence: true, length: { maximum: 50 } # 50文字まで
    # require 'net/http'
    # require "open-uri"
    # require "nokogiri"

    validates :url, :comment, presence: true

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  require 'net/http'
  require "open-uri"
  require 'nokogiri'
  require 'logger'

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @restaurants = Restaurant.all
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
    # @restaurant = Restaurant.all
    # @restaurant = Restaurant.find(2)
    # @restaurant = Restaurant.where(:user_id => current_user.id)
    @restaurant = Restaurant.find(current_user.id)
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
    # スクレイピング先のURL
    restaurant_url = Restaurant.last.url

    ######################################################################
    # yelp
    ######################################################################
    # # image = doc.xpath('//li[@class="mainphoto-box"]/img[@class="mainphoto-image"]').attribute("src").value

    url = Restaurant.last.url

    # スマホURLの対応
    if (restaurant_url.index("m") == 8)
      url = url.gsub("m", "www")
    end

    opt = {}
    opt['User-Agent'] = 'Opera/9.80 (Windows NT 5.1; U; ja) Presto/2.7.62 Version/11.01 '

    charset = nil

    html = open(restaurant_url,opt) do |f|
      charset = f.charset # 文字種別を取得
      f.read # htmlを読み込んで変数htmlに渡す
    end

    # htmlをパース(解析)してオブジェクトを生成
    doc = Nokogiri::HTML.parse(html, nil, charset)

    # 店舗名
    title =  doc.title
    title_num =  doc.title.index("-")
    title = title[0..title_num-2]
    puts title

    # # カテゴリー
    category = doc.xpath('//span[@class="category-str-list"]/a[1]/text()').to_s
    # category2 = doc.xpath('//span[@class="category-str-list"]/a[2]/text()').to_s
    # category3 = doc.xpath('//span[@class="category-str-list"]/a[3]/text()').to_s
    # puts category1
    # puts category2
    # puts category3
    # 価格帯
    price = doc.xpath('//dd[@class="nowrap price-description"]/text()').to_s
    price_head = price.index("￥")

    if price.count("以") > 0
      price_tail = price.index("以上")
    elsif price.count("-") > 0
      price_tail = price.index("-")
    elsif
      price_tail = nil
    end

    if price_tail != nil
      price = price[price_head+1..price_tail-1].delete(",").to_i
    end

    puts price

    # 評価
    star = doc.xpath('//i[@class="star-img stars_4"]').attribute("title").value
    star_num = star.index("星")
    star = star[0..star_num-2]
    puts star
    # エリア
    area = doc.xpath('//span[@class="neighborhood-str-list"]/text()')
    area.index("n")
    puts area
    # イメージ
    image = doc.xpath('//meta[@property="og:image"]').attribute("content").value
    image_url = doc.xpath('//a[@class="see-more show-all-overlay"]').attribute("href").value
    image_url = "https://www.yelp.co.jp/" + image_url + "?tab=food"

    html = open(image_url,opt) do |f|
      charset = f.charset # 文字種別を取得
      f.read # htmlを読み込んで変数htmlに渡す
    end
    # htmlをパース(解析)してオブジェクトを生成
    doc = Nokogiri::HTML.parse(html, nil, charset)
    image = doc.xpath('//meta[@property="og:image"]').attribute("content").value

    ######################################################################

    @restaurant.update(
      :name => title,
      :category => category,
      :price => price,
      :star => star,
      :area => area,
      :image => image
      )

    redirect_to root_path

    else
      render 'new'
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    url = restaurant_params[:url]
    comment = restaurant_params[:comment]
    user_id = restaurant_params[:user_id]
    payment = restaurant_params[:payment]

    # スマホURLの対応
    if (url.index("m") == 8)
      url = url.gsub("m", "www")
    end

    opt = {}
    opt['User-Agent'] = 'Opera/9.80 (Windows NT 5.1; U; ja) Presto/2.7.62 Version/11.01 '

    charset = nil
    html = open(url,opt) do |f|
      charset = f.charset # 文字種別を取得
      f.read # htmlを読み込んで変数htmlに渡す
    end

    # htmlをパース(解析)してオブジェクトを生成
    doc = Nokogiri::HTML.parse(html, nil, charset)

    # 店舗名
    title =  doc.title
    title_num =  doc.title.index("-")
    title = title[0..title_num-2]
    puts title

    # # カテゴリー
    category = doc.xpath('//span[@class="category-str-list"]/a[1]/text()').to_s
    # category2 = doc.xpath('//span[@class="category-str-list"]/a[2]/text()').to_s
    # category3 = doc.xpath('//span[@class="category-str-list"]/a[3]/text()').to_s
    # puts category1
    # puts category2
    # puts category3
    # 価格帯
    price = doc.xpath('//dd[@class="nowrap price-description"]/text()').to_s
    price_head = price.index("￥")

    if price.count("以") > 0
      price_tail = price.index("以上")
    elsif price.count("-") > 0
      price_tail = price.index("-")
    elsif
      price_tail = nil
    end

    if price_tail != nil
      price = price[price_head+1..price_tail-1].delete(",").to_i
    end

    # 評価
    star = doc.xpath('//i[@class="star-img stars_4"]').attribute("title").value
    star_num = star.index("星")
    star = star[0..star_num-2]
    # エリア
    area = doc.xpath('//span[@class="neighborhood-str-list"]/text()')
    area = area.index("n") # ここはあとで修正が必要。areaのxpathの取得ができていない。
    # イメージ
    image = doc.xpath('//meta[@property="og:image"]').attribute("content").value
    image_url = doc.xpath('//a[@class="see-more show-all-overlay"]').attribute("href").value
    image_url = "https://www.yelp.co.jp/" + image_url + "?tab=food"

    html = open(image_url,opt) do |f|
      charset = f.charset # 文字種別を取得
      f.read # htmlを読み込んで変数htmlに渡す
    end
    # htmlをパース(解析)してオブジェクトを生成
    doc = Nokogiri::HTML.parse(html, nil, charset)
    image = doc.xpath('//meta[@property="og:image"]').attribute("content").value

    ######################################################################
    @restaurant.update_all(
      :name => title,
      :category => category,
      :price => price,
      :star => star,
      :area => area,
      :image => image,
      :comment => comment,
      :payment => payment,
      :url => url,
    )
    redirect_to user_path
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy

    @restaurant.destroy
    redirect_to restaurants_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      # @restaurant = Restaurant.find(params[:id])
      @restaurant = Restaurant.where(:user => current_user.id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :category, :price, :star, :area, :image, :comment, :user_id, :payment, :url)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<!-- レストランフォーム -->
<%= form_for(@restaurant) do |f| %>


<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="main">
      <br>
      <%= @restaurant %>

      <center>
        <div class="row">
          <div class="col-xs-4">
            <a href="<%= user_path %>"><i class="fa fa-user fa-3x" aria-hidden="true"></i> &nbsp;</a>
          </div>
          <div class="col-xs-4">
          <a href="/"><i class="fa fa-home fa-3x" aria-hidden="true"></i>&nbsp;</a>
          </div>
          <div class="col-xs-4">

          </div>
        </div>
      </center>


        <div class="male-res">
          <form>
            <div class="male-res-inner">
              <div class="center-content">
                <h3>レストラン入力画面</h3>
              </div>

              <a href="https://www.yelp.co.jp" target="_blank"><i class="fa fa-yelp" aria-hidden="true"></i>https://www.yelp.co.jp</a><br>

              <br>

              <div class="btn-and-input">
                <p><i class="fa fa-square" aria-hidden="true"></i> YelpのURL </p>
                  <%= f.text_field :url, :class => "field male-res-input", :placeholder => "https://www.yelp.co.jp/..." %>
              </div>
              <div class="btn-and-input">
                <p><i class="fa fa-square" aria-hidden="true"></i> 一言コメント </p>
                <%= f.text_area :comment, :class => "field male-res-input", :placeholder => "一言コメントを入力してください" %>
              </div>

<!--                 <% if current_user.gender == "male" %>
                <div class="btn-and-input">
                  <p>▶ 支払いを選択してください </p>
                  <div class="input-radio">
                    <input type="radio" name="" id="">
                    <label for="">奢るよ！</label>
                  </div>
                  <div class="input-radio">
                    <input type="radio"  name="" id="">
                    <label for="">一緒に行こう！</label>
                  </div>
                </div>
                <% end %> -->

              <% if current_user.gender == "male" %>
              <p><i class="fa fa-square" aria-hidden="true"></i> 支払いを選択してください </p>
              <!-- 空欄の場合には「どちらでも！」になります。 -->
                <label><%= f.radio_button :payment, "0" %>奢るよ！</label>
                <label><%= f.radio_button :payment, "1" %>一緒に行こう！</label>
              <% end %>
            </div>
              <%= hidden_field_tag 'restaurant[user_id]', current_user.id %>
              <%= f.submit :class => "male-res-footer lead field action actions btn-block" %>
            </form>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/restaurants/_scrape.html.erb
######################################################################
# yelp
######################################################################
# # image = doc.xpath('//li[@class="mainphoto-box"]/img[@class="mainphoto-image"]').attribute("src").value

# yelpのスクレイピング先のURL
# url = 'https://www.yelp.co.jp/biz/%E3%83%8B%E3%83%A5%E3%83%BC%E3%83%A8%E3%83%BC%E3%82%AF-%E3%82%B0%E3%83%AA%E3%83%AB-%E6%96%B0%E5%AE%BF%E5%8C%BA'

url = Restaurant.last.url

opt = {}
opt['User-Agent'] = 'Opera/9.80 (Windows NT 5.1; U; ja) Presto/2.7.62 Version/11.01 '

charset = nil

html = open(restaurant_url,opt) do |f|
  charset = f.charset # 文字種別を取得
  f.read # htmlを読み込んで変数htmlに渡す
end

# htmlをパース(解析)してオブジェクトを生成
doc = Nokogiri::HTML.parse(html, nil, charset)

# 店舗名
title =  doc.title
title_num =  doc.title.index("-")
title = title[0..title_num-2]
puts title

# # カテゴリー
category = doc.xpath('//span[@class="category-str-list"]/a[1]/text()').to_s
# category2 = doc.xpath('//span[@class="category-str-list"]/a[2]/text()').to_s
# category3 = doc.xpath('//span[@class="category-str-list"]/a[3]/text()').to_s
# puts category1
# puts category2
# puts category3
# 価格帯
price = doc.xpath('//dd[@class="nowrap price-description"]/text()').to_s
price_head = price.index("￥")

if price.count("以") > 0
  price_tail = price.index("以上")
elsif price.count("-") > 0
  price_tail = price.index("-")
elsif
  price_tail = nil
end

if price_tail != nil
  price = price[price_head+1..price_tail-1].delete(",").to_i
end

puts price

# 評価
star = doc.xpath('//i[@class="star-img stars_4"]').attribute("title").value
star_num = star.index("星")
star = star[0..star_num-2]
puts star
# エリア
area = doc.xpath('//span[@class="neighborhood-str-list"]/text()')
area.index("n")
puts area
# イメージ
image = doc.xpath('//meta[@property="og:image"]').attribute("content").value
image_url = doc.xpath('//a[@class="see-more show-all-overlay"]').attribute("href").value
image_url = "https://www.yelp.co.jp/" + image_url + "?tab=food"

html = open(image_url,opt) do |f|
  charset = f.charset # 文字種別を取得
  f.read # htmlを読み込んで変数htmlに渡す
end
# htmlをパース(解析)してオブジェクトを生成
doc = Nokogiri::HTML.parse(html, nil, charset)
image = doc.xpath('//meta[@property="og:image"]').attribute("content").value

######################################################################

app/views/restaurants/edit.html.erb
<!-- <h1>レストラン情報編集画面</h1> -->
<br>

<%= render 'form' %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Restaurants</h1>
<%= link_to '[Top]', "/" %><br/>

<% @restaurants.each do |restaurant| %>
<table>
  <tbody>
    <tr>
      <td>name:</td>
      <td><%= restaurant.name %></td>
      <td rowspan="10"></td>
    </tr>
    <tr>
      <td>category:</td>
      <td><%= restaurant.category %></td>
    </tr>
    <tr>
      <td>price:</td>
      <td><%= restaurant.price %></td>
    </tr>
    <tr>
      <td>star:</td>
      <td><%= restaurant.star %></td>
    </tr>
    <tr>
      <td>image:</td>
      <td><%= restaurant.image %></td>
    </tr>
    <tr>
      <td>Comment:</td>
      <td><%= restaurant.comment %></td>
    </tr>
    <tr>
      <td>User_id:</td>
      <td><%= restaurant.user_id %></td>
    </tr>
    <tr>
      <td>Payment:</td>
      <td><%= restaurant.payment %></td>
    </tr>
    <tr>
      <td>食べログURL:</td>
      <td><%= restaurant.url %></td>
    </tr>
    <tr>
      <td><%= link_to '[Show]', restaurant %>
<%= link_to '[Edit]', edit_restaurant_path(restaurant) %>
<%= link_to '[Destroy]', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <td></td>
    </tr>

    <hr>

<% end %>

</tbody>
</table>

app/views/restaurants/new.html.erb
<!-- <h1>New Restaurant</h1> -->

<%= render 'form' %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @restaurant.category %>
</p>

<p>
  <strong>Price:</strong>
  <%= @restaurant.price %>
</p>

<p>
  <strong>Star:</strong>
  <%= @restaurant.star %>
</p>

<p>
  <strong>Area:</strong>
  <%= @restaurant.area %>
</p>

<p>
  <strong>Image:</strong>
  <%= @restaurant.image %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @restaurant.comment %>
</p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>