config/routes.rb
Rails.application.routes.draw do
  root "flint#index"

  get 'privacy-policy' => 'flint#privacyPolicy'

  resources :restaurants
  get 'restaurant/edit' => 'restaurants#edit'

  resources :messages

  devise_for :users, :controllers => {
    :omniauth_callbacks => 'users/omniauth_callbacks',
    :registrations => 'users/registrations'
  }

  get 'addLike' => 'flint#addLike'
  get 'updateMatch' => 'flint#updateMatch'
  get 'match' => 'flint#match'
  get 'user' => 'flint#user'
  get 'show/:id' => 'flint#show'
  get 'notification' => 'notifications#index'
  get 'create/:url' => "restaurant#create"

end

app/controllers/flint_controller.rb
class FlintController < ApplicationController
    before_action :sign_in_required
    # helper_method :addLike

    def index
        if current_user.gender == "male"
            #異性のid一覧を取得
            gender_like_id = User.select(:id).where(:gender => "female")
        elsif current_user.gender == "female"
            #異性のid一覧を取得
            gender_like_id = User.select(:id).where(:gender => "male")
        else
            if current_user == nil
                redirect_to user_session_path
            else
                render :text => "something wrong"
            end
        end

        #ログインユーザーが、既にselectしている異性レストランid一覧を取得
        selected_gender_restraunt_id = UserLike.select(:restaurant_id).where(:user_id => current_user.id, :like_id => gender_like_id)
        same_gender_id = User.select(:id).where(:gender => current_user.gender)
        #selectされていない異性レストラン一覧を取得
        @candidates = Restaurant.where.not(:id => selected_gender_restraunt_id).where.not(:user_id => same_gender_id)
        # @users = User.where(:id => params[:id])
        @users = User.all
    end

    def new
        @user_like = UserLike.new
    end


    def user
        facebook_uid = nil
        # ここがバグの元↓
        @current_user_candidates = Restaurant.where(:user_id => current_user.id)

        # render :text => Restaurant.all
        @users = User.all

        # Facebook情報取得
        facebook_uid = User.find(current_user.id).uid
        if facebook_uid == nil
            redirect_to root_path
        else
        @facebook_uid_thumb = "https://graph.facebook.com/"+ facebook_uid +"/picture?type=large"
        end
        # facebook_birthday = User.find(current_user.id).birthday
        # facebook_friends = User.find(current_user.id).friends
        # facebook_education = User.find(params[:id]).education
        # facebook_work = User.find(params[:id]).work


    end
    ### ↑たぶん、userメソッドとshowメソッドは一緒にできる。↓　###
    def show # クリックされたユーザのレストラン情報とサムネイル画像
        @select_user_candidate = Restaurant.where(:user_id => params[:id])
        @users = User.where(:id => params[:id])
        facebook_uid = User.find(params[:id]).uid
        @facebook_uid_thumb = "https://graph.facebook.com/"+ facebook_uid +"/picture?type=large"
        # facebook_birthday = User.find(params[:id]).birthday
        # facebook_friends = User.find(params[:id]).friends



        # @facebook_birthday = user.user_birthday
        # @facebook_friends = user.user_friends
    end

    def addLike # like側のuser_idとlikeされる側のuser_idをデータベース（user_like）に入れる
  		# モデルオブジェクトを生成
		# @user_like = UserLike.new
		# 属性を設定してモデルオブジェクトを生成
		# @user_like = UserLike.new(:user_id => 25 , :like_id => 28)
		# params変更


        #今回は、addlikeがrestaurantについておされるので、以下をしらべる
            # like_idがcurrent_userで
            # user_idが押した相手で
            # restaurant_idの店
        @match = UserLike.where(:user_id => params[:l_id], :like_id => current_user.id, :restaurant_id => params[:restaurant_id]).where.not(:matching => 0)

        if @match.exists?
            #すでに押されていて1:片方のみのいいねなら普通にマッチ
            if @match.first.matching == 1
                @match.first.update(:matching => 3)
            elsif @match.first.matching == 2
                @match.first.update(:matching => 4)
            end
            @match.first.save
            redirect_to root_path
        else
            @user_like = UserLike.new(:user_id => current_user.id, :like_id => params[:l_id], :restaurant_id => params[:restaurant_id], :matching => params[:matching])
            if @user_like.save
                else
                render 'new'
            end
            redirect_to root_path
        end
    end

    def updateMatch
        UserLike.find(params[:userlike_id]).update(:matching => params[:matching])
        redirect_to root_path
    end

  #ログイン中ユーザーのマッチした一覧を表示
  def match
    @matches = UserLike.where(:user_id => current_user.id, :matching => 1)
  end

  def privacyPolicy
    render 'privacyPolicy'
  end


end

app/helpers/flint_helper.rb
module FlintHelper
end

app/views/flint/index.html.erb
<div class="container">
  <br>
  <center>
    <div class="row">
      <div class="col-xs-4">
        <a href="<%= user_path %>"><i class="fa fa-user fa-3x" aria-hidden="true"></i> &nbsp;</a>
      </div>
      <div class="col-xs-4">
        <strong ><%= current_user.name %>.<%= current_user.age_range %> <%= current_user.birthday %></strong>
      </div>
      <div class="col-xs-4">
        <a href="<%= notification_path %>"><i class="fa fa-bell-o fa-3x" aria-hidden="true"></i>&nbsp;</a>
      </div>
    </div>
  </center>

  <br>

  <% @candidates.each do |candidate| %>
  <div class="main">
    <div class="woman-pick roll-fixing">
      <div class="woman-pick-inner">

        <!-- レストランの画像 -->
        <div class="woman-pick-pic">
          <img src="<%= candidate.image %>" alt="image" class="pick-top-img" style ="width: 100%; background-size: cover;"/>
          <div class="woman-pick-profile-pic pick-profile-pic-trim">
            <img src="<%= @users.find(candidate.user_id).thumb %>" alt="..." >
          </div>
        </div>

        <!-- ユーザ情報とレストラン情報 -->
        <div class="woman-pick-profile">
          <div class="woman-pick-profile-text">
            <h5><%= candidate.user_id %>：<strong><%= @users.find(candidate.user_id).name %></strong>.<%= @users.find(candidate.user_id).age_range %> <i class="fa fa-users" aria-hidden="true"></i></h5>
            <p><%= @users.find(candidate.user_id).job %></p>
          </div>
        </div>

        <div class="pick-text-pad">
          <h4 ><%= candidate.name %></h4>
          <%= link_to '[もっと見る]', :controller => "flint", :action => "show", :id => candidate.user_id, :class => "btn btn-danger btn-xs" %>
          <ul class="woman-pick-list">
            <li>
              <!-- ここに星数えて表示する奴 -->
            <% if candidate.star.present? %>
              <% for starNum in 1..candidate.star do %>
                <i class="fa fa-star" aria-hidden="true"></i>
              <% end %>
            <% else %>
              評価なし
            <% end %>
            </li>
            <li>
              <%= candidate.star %>
            </li>
            <li>
              <% if @users.find(candidate.user_id).gender == "male" %>
              <div class="btn-danger btn-xs disabled">
                <% if candidate.payment == 0 %>
                奢るよ！
                <% elsif candidate.payment == 1 %>
                割り勘で！
                <% else %>
                どちらでも！
                <% end %>
              </div>
              <% end %>
            </li>
          </ul>
          <ul class="woman-pick-list">
            <li>
              <span class="border-text">カテゴリ</span>
              <span><%= candidate.category %></span>
            </li>
            <li>
              <span class="border-text">価格</span>
              <span><%= candidate.price %></span>
            </li>
            <li>
              <span class="border-text">エリア</span>
              <span><%= candidate.area %></span>
            </li>
          </ul>




        </div>

      <!-- 男性だった場合のボタン -->
      <% if current_user.gender == "male" %>
      <div class="cir-btn-table" style="padding-top: 20px">
        <div class="cir-btn-table-cell">
          <div class="cir-btn cir-btn-blue">
            <%= link_to "✕", :controller => "flint", :action => "addLike", :l_id => candidate.user_id, :matching => 0,:restaurant_id => candidate.id, :matching => 0, :method => :post %>
            <!-- <i class="fa fa-times" aria-hidden="true"></i> -->
          </div>
          <p>✕</p>
        </div>
        <div class="cir-btn-table-cell">
          <div class="cir-btn cir-btn-red">
            <%= link_to "◯", :controller => "flint", :action => "addLike", :l_id => candidate.user_id, :restaurant_id => candidate.id, :matching => 1, :matching => 1, :method => :post %>
            <!-- <i class="fa fa-circle-o" aria-hidden="true"></i> -->
          </div>
          <p>ワリカン！</p>
        </div>
        <div class="cir-btn-table-cell">
          <div class="cir-btn cir-btn-orange">
            <%= link_to "♡", :controller => "flint", :action => "addLike", :l_id => candidate.user_id, :restaurant_id => candidate.id, :matching => 2, :method => :post %>
            <!-- <i class="fa fa-heart" aria-hidden="true"></i> -->
          </div>
          <p>おごる！</p>
        </div>
      </div>

      <!-- 女性だった場合のボタン -->
      <% elsif current_user.gender == "female" %>
      <div class="cir-btn-table">
        <div class="cir-btn-table-cell">
          <div class="cir-btn cir-btn-blue">
            <%= link_to "✕", :controller => "flint", :action => "addLike", :l_id => candidate.user_id, :restaurant_id => candidate.id, :matching => 0, :method => :post , :class => " fa fa-heart" %>
          </div>
          <p>bad</p>
        </div>
        <div class="cir-btn-table-cell">
          <div class="cir-btn cir-btn-red">
            <%= link_to "◯", :controller => "flint", :action => "addLike", :l_id => candidate.user_id, :restaurant_id => candidate.id, :matching => 1, :method => :post, :class => " fa fa-heart" %>
          </div>
          <p>Like</p>
        </div>
      </div>
      </div>
      <% end %>


    </div>
  </div>

<% end %>
  </div>

app/views/flint/match.html.erb
<!-- マッチ一覧 -->
<div class="container">
<button type="button" class="btn btn-default"><%= link_to '<', "/" %></button>
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<div class="main">
				<div class="notice-index">
					<% @matches.each do |match| %>
					<ul class="notice-table">
						<li>
							<div class="notice-img">
								<img src="/assets/girl1.jpg" alt="..." class="img-circle" />
							</div>
							<div class="notice-text">
								<h4>USER_ID:<%= link_to match.id, :controller => "messages", :action => "show", :id => match.id, :current => current_user.id %>番とマッチしています。</h4>
							</div>
						</li>
					</ul>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>
</div>

app/views/flint/privacyPolicy.html.erb
<div class ="pbody">
Flint（以下「当サービス」）は、以下のとおり個人情報保護方針を定め、個人情報保護の仕組みを構築し、個人情報保護の重要性の認識と取組みを徹底させることにより、個人情報の保護を推進致します。
<h4>個人情報の管理</h4>
当サービスは、お客さまの個人情報を正確かつ最新の状態に保ち、個人情報への不正アクセス・紛失・破損・改ざん・漏洩などを防止するため、セキュリティシステムの維持・管理体制の整備等の必要な措置を講じ、安全対策を実施し個人情報の厳重な管理を行ないます。
<h4>個人情報の利用目的</h4>
お客さまからお預かりした個人情報は、当サービス上での氏名、年齢、アプリを使用している共通の友人、アイコン画像の表示に利用いたします。
<h4>個人情報の第三者への開示・提供の禁止</h4>
当サービスは、お客さまよりお預かりした個人情報を適切に管理し、次のいずれかに該当する場合を除き、個人情報を第三者に開示いたしません。
<li>お客さまの同意がある場合</li>
<li>お客さまが希望されるサービスを行なうために当サービスが業務を委託する業者に対して開示する場合</li>
<li>法令に基づき開示することが必要である場合</li>
<h4>個人情報の安全対策</h4>
当サービスは、個人情報の正確性及び安全性確保のために、セキュリティに万全の対策を講じています。
<h4>ご本人の照会</h4>
お客さまがご本人の個人情報の照会・修正・削除などをご希望される場合には、ご本人であることを確認の上、対応させていただきます。
<h4>法令、規範の遵守と見直し</h4>
当サービスは、保有する個人情報に関して適用される日本の法令、その他規範を遵守するとともに、本ポリシーの内容を適宜見直し、その改善に努めます。
</div>

app/views/flint/show.html.erb
<!-- 選択したユーザの詳細情報 -->
<br>

<div class="container">
<center><a href="/"><i class="fa fa-home fa-3x" aria-hidden="true"></i>&nbsp;</a></center>
</div>
<hr>
<% @select_user_candidate.each do |candidate| %>
<div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="main">
          <div class="fem-profile">

          <% @users.each do |user| %>
            <div class="fem-profile-part-1">
              <img src="<%= @facebook_uid_thumb %>" alt="" style ="width: 100%; background-size: cover;"/>
            </div>
            <div class="fem-profile-part-2">
              <h4>
                <strong><%= user.id %>：<%= user.name %></strong>.<%= user.age_range %> <i class="fa fa-users" aria-hidden="true"></i>
              </h4>
              <p>
                <% if @users.find(candidate.user.id).introduction == nil %>
                  nil
                <% else %>
                  <%= @users.find(candidate.user.id).introduction %>
                <% end %>
              </p>
            </div>
            <div class="fem-profile-part-2">
              <h4>共通の友人</h4>
              <ul class="woman-pick-list">
                <li>
                <!-- ここの共通の友人の表示 -->
                  <%= @users.find(candidate.user.id).friends %>
              </li>
              </ul>
            </div>
            <div class="fem-profile-part-2">
              <h4>レストラン</h4>
            </div>
            <img src="<%= candidate.image %>" alt="image" style ="width: 100%; background-size: cover;"/>
            <div class="fem-profile-part-2">
              <div class="male-msg-top-text">
                <h4><%= candidate.name %></h4>
                <ul class="woman-pick-list">
                  <li>
                    <% for starNum in 1..candidate.star do %>
                      <i class="fa fa-star" aria-hidden="true"></i>
                    <% end %>
                  </li>
                  <li>
                    <%= candidate.star %>
                  </li>
                  <li>
                  <% if user.gender == "male" %>
                      <div class="btn-danger btn-xs disabled">
                        <% if candidate.payment == 0 %>
                            奢るよ！
                        <% elsif candidate.payment == 1 %>
                            割り勘で！
                        <% else %>
                            どちらでも！
                        <% end %>
                      </div>
                  <% end %>
                  </li>

                </ul>
                <ul class="woman-pick-list">
                  <li>
                    <span class="border-text">カテゴリ</span>
                    <span><%= candidate.category %></span>
                  </li>
                  <li>
                    <span class="border-text">価格帯</span>
                    <span><%= candidate.price %>~</span>
                  </li>
                  <li>
                    <span class="border-text">エリア</span>
                    <span><%= candidate.area %></span>
                  </li>
                </ul>

                <!-- 男性だった場合の選択ボタン -->
                <% if current_user.gender == "male" %>
                <div class="fem-profile-table row">
                <div class="col-xs-3">
                  <div class="pick-profile-pic-trim" style="width: 50px; height: 50px;">
                    <img src="<%= user.thumb %>" alt="...">
                  </div>
                  </div>
                    <div class="baloon col-xs-9">
                    <%= candidate.comment %>
                    </div>
                </div>
                <div class="cir-btn-table" style="padding-top: 20px">
                  <div class="cir-btn-table-cell">
                    <div class="cir-btn cir-btn-blue">
                      <!-- <i class="fa fa-times" aria-hidden="true"></i> -->
                      <%= link_to "✕", :controller => "flint", :action => "addLike", :l_id => candidate.user_id, :matching => 0,:restaurant_id => candidate.id, :matching => 0, :method => :post %>
                    </div>
                    <p>行かない</p>
                  </div>
                  <div class="cir-btn-table-cell">
                    <div class="cir-btn cir-btn-red">
                      <!-- <i class="fa fa-heart" aria-hidden="true"></i> -->
                      <%= link_to "◯", :controller => "flint", :action => "addLike", :l_id => candidate.user_id, :restaurant_id => candidate.id, :matching => 1, :matching => 1, :method => :post %>
                    </div>
                    <p>ワリカン！</p>
                  </div>
                  <div class="cir-btn-table-cell">
                    <div class="cir-btn cir-btn-orange">
                      <!-- <i class="fa fa-star" aria-hidden="true"></i> -->
                      <%= link_to "♡", :controller => "flint", :action => "addLike", :l_id => candidate.user_id, :restaurant_id => candidate.id, :matching => 2, :method => :post %>
                    </div>
                    <p>奢るよ！</p>
                  </div>
                </div>

                <!-- 女性だった場合の選択ボタン -->
                <% elsif current_user.gender == "female" %>
                 <div class="fem-profile-table row">
                 <div class="col-xs-3">
                    <div class="pick-profile-pic-trim" style="width: 50px; height: 50px;">
                      <img src="<%= user.thumb %>" alt="...">
                    </div>
                    </div>
                  <div class="baloon col-xs-9">
                    <%= candidate.comment %>
                  </div>
                </div>
                <div class="cir-btn-table">
                  <div class="cir-btn-table-cell">
                    <div class="cir-btn cir-btn-blue">
                      <!-- <i class="fa fa-times" aria-hidden="true"></i> -->
                      <%= link_to "✕", :controller => "flint", :action => "addLike", :l_id => candidate.user_id, :restaurant_id => candidate.id, :matching => 0, :method => :post , :class => " fa fa-heart" %>
                    </div>
                    <p>行かない</p>
                  </div>
                  <div class="cir-btn-table-cell">
                    <div class="cir-btn cir-btn-red">
                      <!-- <i class="fa fa-heart" aria-hidden="true"></i> -->
                      <%= link_to "◯", :controller => "flint", :action => "addLike", :l_id => candidate.user_id, :restaurant_id => candidate.id, :matching => 1, :method => :post, :class => " fa fa-heart" %>
                    </div>
                    <p>行きたい</p>
                  </div>
                </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
  </div>
  <% end %>


   <!-- 男女別選択肢ボタン -->
        <!--<% if current_user.gender == "male" %>
          <p class = "btn btn-default"><%= link_to "☓", :controller => "flint", :action => "addLike", :u_id => current_user.id, :l_id => candidate.user, :restaurant_id => 0, :method => :post %></p>

          <p class = "btn btn-default"><%= link_to "ワリカン！", :controller => "flint", :action => "addLike", :u_id => current_user.id, :l_id => candidate.user, :restaurant_id => 1, :method => :post %></p>

          <p class = "btn btn-default"><%= link_to "おごる！", :controller => "flint", :action => "addLike", :u_id => current_user.id, :l_id => candidate.user, :restaurant_id => 2, :method => :post %></p>

        <% elsif current_user.gender == "female" %>
          <p class = "btn btn-default"><%= link_to "☓", :controller => "flint", :action => "addLike", :u_id => current_user.id, :l_id => candidate.user, :restaurant_id => 0, :method => :post %></p>

          <p class = "btn btn-default"><%= link_to "行きたい！", :controller => "flint", :action => "addLike", :u_id => current_user.id, :l_id => candidate.user, :restaurant_id => 1, :method => :post %></p>
         <% end %> -->
<% end %>

app/views/flint/user.html.erb
<!-- ログインしているユーザの情報 -->
<br>
<center>
  <div class="row">
    <div class="col-xs-4">
      <a href= "<%= edit_user_registration_path %>"><i class="fa fa-cog fa-3x" aria-hidden="true"></i>&nbsp;</a>
    </div>
    <div class="col-xs-4">
      <a href="/"><i class="fa fa-home fa-3x" aria-hidden="true"></i>&nbsp;</a>
    </div>
    <div class="col-xs-4">
      <a href="/restaurant/edit"><i class="fa fa-cutlery fa-3x" aria-hidden="true"></i>&nbsp;</a>
    </div>
  </div>
</center>

<hr>

<!-- ユーザ情報 -->
<div class="container">
<center><h4><i class="fa fa-user fa-3x" aria-hidden="true"></i> &nbsp;</h4></center>
  <div class="main">
    <div class="fem-profile">
      <div class="fem-profile-part-1">
        <img src="<%= @facebook_uid_thumb %>" alt="" style ="width: 100%; background-size: cover;"/>
        <!-- <img src="<%= @facebook_uid_thumb %>" alt="" /> -->
      </div>
      <div class="fem-profile-part-2">
        <h4>
          <%= current_user.id %>：<strong><%= current_user.name %></strong>.<%= current_user.age_range %> <i class="fa fa-users" aria-hidden="true"></i>
        </h4>
        <p>
          <%= @users.find(current_user.id).job %>
        </p>
        <p>
        <% if @users.find(current_user.id).introduction == nil %>
          nil
        <% else %>
          <%= @users.find(current_user.id).introduction %>
        <% end %>
        </p>
      </div>

      <div class="fem-profile-part-2">
        <h4>レストラン情報</h4>
      </div>

<% @current_user_candidates.each do |candidate| %>
      <img src="<%= candidate.image %>" alt="image" style ="width: 100%; background-size: cover;"/>
      <div class="fem-profile-part-2">
        <div class="male-msg-top-text">
          <h4><%= candidate.name %></h4>
          <ul class="woman-pick-list">
            <li>
             <!-- ここに星の評価 -->
            <% if candidate.star.present? %>
              <% for starNum in 1..candidate.star do %>
                <i class="fa fa-star" aria-hidden="true"></i>
              <% end %>
            <% else %>
              評価なし
            <% end %>
            </li>
            <li>
              <%= candidate.star %>
            </li>
            <li>
              <% if @users.find(current_user.id).gender == "male" %>
              <div class="btn-danger btn-xs disabled">
                <% if candidate.payment == 0 %>
                奢るよ！
                <% elsif candidate.payment == 1 %>
                割り勘で！
                <% else %>
                どちらでも！
                <% end %>
              </div>
              <% end %>
            </li>
          </ul>
          <ul class="woman-pick-list">
            <li>
              <span class="border-text">カテゴリ</span>
              <span><%=candidate.category %></span>
            </li>
            <li>
              <span class="border-text">価格帯</span>
              <span><%= candidate.price %>~</span>
            </li>
            <li>
              <span class="border-text">エリア</span>
              <span><%= candidate.area %></span>
            </li>
          </ul>

          <div class="fem-profile-table row">
            <div class="col-xs-3">
              <div class="pick-profile-pic-trim" style="width: 50px; height: 50px; margin-top: 100px;">
                <img src="<%= @users.find(current_user.id).thumb %>" alt=''>
              </div>
            </div>
              <div class="baloon col-xs-9">
                <%= candidate.comment %>
              </div>
          </div>
        </div>
      </div>
<% end %>
    </div>
  </div>
</div>